#!/usr/bin/perl

use strict;
use warnings;
use Encode;

my ($fichier) = @ARGV;

my $fic_contenu   = $fichier . ".tex";
my $fic_squelette = $fichier . ".skel";

open my $f, $fic_contenu
  or die "ouverture $fic_contenu $!";
my @source = <$f>;
close $f
  or die "fermeture $fic_contenu $!";
my @dest;
my %ref;

for (@source) {
  Encode::from_to($_, "utf8", "iso-8859-1");

  if (/\\.*section\*\{(?:\d+\.\s*)?(.*?)\\label\{(.*?)\}/) {
    my $cle = lc($1);
    $cle =~ tr/\xc9/\xe9/;
    $ref{$cle} = $2;
  }
}

#print STDERR "Hachage \%ref :\n";
#for (sort keys %ref) {
#  print STDERR $_, " -> ", $ref{$_}, "\n";
#}
for (@source) {

  s/1re/1\\re{}/g;
  s/\bTM\b/\\tm{}/g;
  s/\bLATEX\b/\\LaTeX{}/g;

  if (/\\(?:textsf|emph)\{(.*?)\} --- p\.\d+/) {
    my $ref = $ref{lc($1)};
    if ($ref) {
      s/p\.\d+/p\.\\pageref\{$ref\}/;
      #print STDERR "Modification $_";
    }
    else {
      #print STDERR "Référence pour '$1' introuvable\n";
    }
  }

  push @dest, $_;
}

open my $sk, $fic_squelette
  or die "ouverture $fic_squelette $!";
open $f, '>', $fic_contenu
  or die "ouverture $fic_contenu $!";
while (<$sk>) {
  if (/^\\input\{$fichier\}$/) {
    for (@dest) {
      print $f $_;
    }
  }
  else {
    print $f $_;
  }
}
close $sk
  or die "fermeture $fic_squelette $!";
close $f
  or die "fermeture $fic_contenu $!";
